DROP TABLE IF EXISTS USERS CASCADE;
DROP SEQUENCE IF EXISTS USER_SEQ;

CREATE SEQUENCE USER_SEQ;
CREATE TABLE USERS(
USER_ID INTEGER NOT NULL DEFAULT NEXTVAL('USER_SEQ') ,
USERNAME VARCHAR(45) NOT NULL UNIQUE,
PASSWORD VARCHAR(255) NOT NULL,
ENABLED SMALLINT NOT NULL DEFAULT 1
);


DROP TABLE IF EXISTS USER_ROLES CASCADE;
DROP SEQUENCE IF EXISTS USER_ROLE_SEQ;


CREATE SEQUENCE USER_ROLE_SEQ;
CREATE TABLE USER_ROLES(
USER_ROLE_ID INTEGER NOT NULL DEFAULT NEXTVAL('USER_ROLE_SEQ') ,
USERNAME  VARCHAR(45) NOT NULL,
ROLE  VARCHAR(45) NOT NULL
);



DROP TABLE IF EXISTS API_KEYS CASCADE;
DROP SEQUENCE IF EXISTS API_KEYS_SEQ;


CREATE SEQUENCE API_KEYS_SEQ;
CREATE TABLE API_KEYS(
ID INTEGER NOT NULL DEFAULT NEXTVAL('API_KEYS_SEQ'),
APP VARCHAR(2000) NOT NULL,
APINAME VARCHAR(200) NOT NULL,
KEY VARCHAR(2000) NOT NULL,
CONSTRAINT UK_API_KEYS UNIQUE (APP,APINAME)
);


INSERT INTO API_KEYS ( APP, APINAME , KEY)
VALUES 
('EDS', 'getEmpImage','9e8d4b7c-6369-442b-a4e7-831d568e9829'),
('EDS', 'getEmployeesChangedSince','f2001028-1bf9-4482-a5c0-57fc1c84065c'),
('EDS', 'getEmployees' ,'c58df84a-a7f9-49d7-bda7-f420b9c9b566'),
('DOCSEARCH', 'getDocument','df25b074-9755-4163-bfd4-9f93c4d43611'),
('DOCSEARCH','getAllTags', 'cef732fe-17a5-4566-9b62-ea9b5774b1b0');


--default admin User
INSERT INTO USER_ROLES (USERNAME, ROLE) VALUES ('admin','ROLE_ADMIN'),('admin','ROLE_USER');

--BASE64 encode is YWRtaW46RiFkZWxpdHlAITIzNA== 
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES('admin', 'vdtOOV6EH0LvHLy8S5Amq6l/x5NKxMaIKQXUWveKg0o=', 1);
